-- ==============================================================================
-- 🌟 COMPLETE & CLEAN SUPABASE DATABASE ARCHITECTURE FOR SAIFEDDINE BOUMAZA
-- Project: kbioxkoifvyivhkzbxke
-- Description: Zero-Friction Setup with AUTOMATIC IDs for ALL tables.
--              You NEVER need to enter an "id" when inserting rows!
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 🧹 STEP 1: CLEAN UP ALL OBSOLETE LEGACY TABLES & OLD FLASH DATA
-- (Drops old tables so your dashboard has ONLY clean trading data with zero legacy rows)
-- ------------------------------------------------------------------------------
DROP TABLE IF EXISTS public.messages CASCADE;
DROP TABLE IF EXISTS public.settings CASCADE;
DROP TABLE IF EXISTS public.offers CASCADE;
DROP TABLE IF EXISTS public.website_prices CASCADE;
DROP TABLE IF EXISTS public.website_settings CASCADE;
DROP TABLE IF EXISTS public.client_reviews CASCADE;
DROP TABLE IF EXISTS public.payout_records CASCADE;


-- ------------------------------------------------------------------------------
-- 📬 TABLE 1: client_messages (استفسارات ورسائل الزوار والمستثمرين)
-- Auto-ID: You DO NOT need to enter "id". It is generated automatically (1, 2, 3...)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.client_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_sent TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    client_name TEXT NOT NULL,
    client_email TEXT NOT NULL,
    preferred_platform TEXT DEFAULT 'Telegram',
    client_handle TEXT DEFAULT '',
    direct_link TEXT DEFAULT '',
    inquiry_topic TEXT DEFAULT 'General Inquiry',
    client_message TEXT NOT NULL,
    status TEXT DEFAULT 'New Message'
);

-- Ensure auto identity sequence if table already existed with older schema
DO $$ 
BEGIN 
    ALTER TABLE public.client_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY; 
EXCEPTION 
    WHEN others THEN NULL; 
END $$;

ALTER TABLE public.client_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public insert to client_messages" ON public.client_messages;
CREATE POLICY "Allow public insert to client_messages"
ON public.client_messages FOR INSERT TO anon, authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated read client_messages" ON public.client_messages;
CREATE POLICY "Allow authenticated read client_messages"
ON public.client_messages FOR SELECT TO authenticated
USING (true);

DROP POLICY IF EXISTS "Allow authenticated manage client_messages" ON public.client_messages;
CREATE POLICY "Allow authenticated manage client_messages"
ON public.client_messages FOR ALL TO authenticated
USING (true);


-- ------------------------------------------------------------------------------
-- ⭐ TABLE 2: client_reviews (آراء وتقييمات العملاء والمستثمرين)
-- Auto-ID: You DO NOT need to enter "id". It is generated automatically (1, 2, 3...)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.client_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    client_name TEXT NOT NULL,
    client_country TEXT DEFAULT 'DZ 🇩🇿',
    rating INT DEFAULT 5,
    service_type TEXT DEFAULT 'managed', -- 'managed', 'signals', 'indicators'
    review_text TEXT NOT NULL,
    review_text_en TEXT,
    profit_stat TEXT DEFAULT '',
    is_verified BOOLEAN DEFAULT true,
    is_active BOOLEAN DEFAULT true
);

DO $$ 
BEGIN 
    ALTER TABLE public.client_reviews ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY; 
EXCEPTION 
    WHEN others THEN NULL; 
END $$;

ALTER TABLE public.client_reviews ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public insert client_reviews" ON public.client_reviews;
CREATE POLICY "Allow public insert client_reviews"
ON public.client_reviews FOR INSERT TO anon, authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read client_reviews" ON public.client_reviews;
CREATE POLICY "Allow public read client_reviews"
ON public.client_reviews FOR SELECT TO anon, authenticated
USING (is_active = true);

DROP POLICY IF EXISTS "Allow authenticated manage client_reviews" ON public.client_reviews;
CREATE POLICY "Allow authenticated manage client_reviews"
ON public.client_reviews FOR ALL TO authenticated
USING (true);

-- Insert Default Verified Reviews (Auto-IDs applied):
INSERT INTO public.client_reviews (client_name, client_country, rating, service_type, review_text, review_text_en, profit_stat, is_verified, is_active)
VALUES
    ('Tariq B.', 'الجزائر 🇩🇿', 5, 'managed', 'بدأت مع سيف الدين بمحفظة تجريبية ثم قمت برفع رأس المال. الالتزام بإدارة المخاطر ووقف الخسارة لا مثيل له، لا مغامرات ولا عشوائية، تقارير أسبوعية تفصيلية واحترافية عالية جداً.', 'Started with Saifeddine on a test portfolio then scaled my capital. The risk management and stop-loss discipline are second to none—zero reckless gambling. Detailed weekly reports and immense professionalism.', '+42.8% ROI (5 أشهر)', true, true),
    ('Faisal Al-Otaibi', 'السعودية 🇸🇦', 5, 'signals', 'أفضل قناة توصيات دخلت فيها من 3 سنوات. نقاط الدخول دقيقة جداً مع وقف خسارة صغير وأهداف محددة. قناة سيف الدين أنقذت حسابي من الخسائر المتراكمة وعوضت رأس مالي.', 'Hands down the best signal channel I have joined in 3 years. Precision entry points, tight stop-losses, and well-defined targets. Saifeddine VIP channel turned my losses into consistent profits.', 'Winrate 86% على الذهب XAUUSD', true, true),
    ('Karim Mansouri', 'فرنسا 🇫🇷', 5, 'newsx', 'منصة NewsX AI رائعة جداً في وقت صدور أخبار الـ CPI والـ NFP. الترجيح المسبق لاتجاه الذهب وفر علي ساعات من التحليل وساعدني في تحقيق صفقات موفقة جداً.', 'The NewsX AI platform is exceptional during high-impact CPI and NFP news releases. Pre-release directional bias on Gold saved me hours of analysis and led to outstanding trade executions.', 'اشتراك NewsX AI · ترجيح دقيق', true, true),
    ('Omar Al-Shammari', 'الإمارات 🇦🇪', 5, 'managed', 'الشفافية هي الرقم 1 عند الأخ سيف الدين. حسابي في Exness مربوط مباشرة وأرى كل صفقة تفتح وتغلق في نفس اللحظة مع الالتزام الصارم بنسبة 1-2% ريسك لكل صفقة.', 'Transparency is unmatched with brother Saifeddine. My Exness account is linked directly; I watch every trade open and close in real-time with strict 1-2% risk discipline per trade.', 'سحب أرباح شهري منتظم', true, true),
    ('David Henderson', 'بريطانيا 🇬🇧', 5, 'indicators', 'مؤشر MT5 المخصص لكسر التقلبات يعمل بكفاءة استثنائية وبدون أي إعادة رسم (Zero Repaint). تعليمات التثبيت واضحة والتسليم فوري على نظام ويندوز.', 'The custom MT5 volatility break indicator works flawlessly without repainting. Clean setup instructions and instant delivery on Windows. Excellent quantitative coding.', 'MT5 Indicator · 0 Repaint', true, true),
    ('Youssef Benali', 'المغرب 🇲🇦', 5, 'newsx', 'تطبيق NewsX AI سريع وخفيف على الهاتف، إشعارات الأخبار تصل قبل حركة السوق بثوانٍ حاسمة. احترافية عالية ودعم فني متواصل من الأخ سيف الدين.', 'The NewsX AI app is lightning fast on mobile. Push alerts arrive right before explosive market volatility. True quantitative edge and continuous support from Saifeddine.', 'ترجيح الذهب XAUUSD · تنبيهات', true, true)
ON CONFLICT DO NOTHING;


-- ------------------------------------------------------------------------------
-- 💵 TABLE 3: payout_records (سحوبات Exness الموثقة وإثباتات الدفع)
-- Auto-ID: You DO NOT need to enter "id". It is generated automatically (1, 2, 3...)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.payout_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    type TEXT DEFAULT 'double', -- 'double' (Exness + Binance) or 'ledger' (Exness direct)
    amount TEXT NOT NULL,
    date TEXT NOT NULL,
    date_ar TEXT DEFAULT '',
    account TEXT DEFAULT 'Exness Real MT5',
    invoice TEXT DEFAULT '',
    binance_order TEXT DEFAULT '',
    binance_time TEXT DEFAULT '',
    speed TEXT DEFAULT '~1-2 Min',
    speed_ar TEXT DEFAULT '~1-2 دقيقة',
    exness_img TEXT DEFAULT '',
    binance_img TEXT DEFAULT '',
    is_verified BOOLEAN DEFAULT true,
    is_active BOOLEAN DEFAULT true,
    display_order INT DEFAULT 0
);

DO $$ 
BEGIN 
    ALTER TABLE public.payout_records ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY; 
EXCEPTION 
    WHEN others THEN NULL; 
END $$;

ALTER TABLE public.payout_records ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read payout_records" ON public.payout_records;
CREATE POLICY "Allow public read payout_records"
ON public.payout_records FOR SELECT TO anon, authenticated
USING (is_active = true);

DROP POLICY IF EXISTS "Allow authenticated manage payout_records" ON public.payout_records;
CREATE POLICY "Allow authenticated manage payout_records"
ON public.payout_records FOR ALL TO authenticated
USING (true);

-- Insert Current 10 Audited Exness Cashouts (Auto-IDs applied):
INSERT INTO public.payout_records (type, amount, date, date_ar, account, invoice, binance_order, binance_time, speed, speed_ar, exness_img, binance_img, is_verified, is_active, display_order)
VALUES
    ('double', '$3,150.51 USD', '11 Sep 2026, 14:11', '11 سبتمبر 2026 - 14:11', 'ex 256505258', '807876734982', '441672878207459329', '14:12:42 UTC', '1m 42s', 'دقيقة و 42 ثانية', 'proofs/payout-1-exness.png', 'proofs/payout-1-binance.png', true, true, 1),
    ('double', '$1,555.00 USD', '19 May 2026, 12:35', '19 مايو 2026 - 12:35', 'ex 256511737', '676651208710', '441672878207459329', '12:37:42 UTC', '2m 42s', 'دقيقتين و 42 ثانية', 'proofs/payout-2-exness.png', 'proofs/payout-2-binance.png', true, true, 2),
    ('double', '$1,026.00 USD', '18 May 2026, 13:36', '18 مايو 2026 - 13:36', 'ex 256505258', '675581050886', '441672878207459329', '13:37:42 UTC', '1m 42s', 'دقيقة و 42 ثانية', 'proofs/payout-3-exness.png', 'proofs/payout-3-binance.png', true, true, 3),
    ('double', '$723.00 USD', '18 May 2026, 02:13', '18 مايو 2026 - 02:13', 'ex 256505258', '674909700102', '441672878207459329', '02:14:42 UTC', '1m 42s', 'دقيقة و 42 ثانية', 'proofs/payout-4-exness.png', 'proofs/payout-4-binance.png', true, true, 4),
    ('double', '$1,522.00 USD', '15 May 2026, 15:54', '15 مايو 2026 - 15:54', 'ex 256497449', '673924100102', '441672878207459329', '15:56:42 UTC', '2m 42s', 'دقيقتين و 42 ثانية', 'proofs/payout-5-exness.png', 'proofs/payout-5-binance.png', true, true, 5),
    ('double', '$1,129.00 USD', '15 May 2026, 14:33', '15 مايو 2026 - 14:33', 'ex 256497174', '673759997958', '441672878207459329', '14:33:42 UTC', 'Instant (< 1m)', 'فوري (أقل من دقيقة)', 'proofs/payout-6-exness.png', 'proofs/payout-6-binance.png', true, true, 6),
    ('ledger', '$4,278.81 USD', '28 Aug 2026, 16:24', '28 أغسطس 2026 - 16:24', 'ex 256505258', '788728934406', '', '', 'Instant', 'فوري', 'proofs/payout-7-exness.png', '', true, true, 7),
    ('ledger', '$1,500.00 USD', '12 Aug 2026, 14:42', '12 أغسطس 2026 - 14:42', 'ex 256698295', '768002146310', '', '', 'Instant', 'فوري', 'proofs/payout-8-exness.png', '', true, true, 8),
    ('ledger', '$500.00 USD', '22 May 2026, 14:08', '22 مايو 2026 - 14:08', 'ex 256516464', '680002113542', '', '', 'Instant', 'فوري', 'proofs/payout-9-exness.png', '', true, true, 9),
    ('ledger', '$575.00 USD', '21 May 2026, 12:00', '21 مايو 2026 - 12:00', 'ex 256516464', '678917492742', '', '', 'Instant', 'فوري', 'proofs/payout-10-exness.png', '', true, true, 10)
ON CONFLICT DO NOTHING;


-- ------------------------------------------------------------------------------
-- 🏷️ TABLE 4: website_prices (باقات وخدمات التداول الحقيقية)
-- Auto-ID: You DO NOT need to enter "id". It is generated automatically (1, 2, 3...)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.website_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_key TEXT UNIQUE NOT NULL,
    item_name TEXT NOT NULL,
    current_price NUMERIC NOT NULL,
    old_price NUMERIC DEFAULT 0,
    discount_tag TEXT DEFAULT '',
    duration TEXT DEFAULT '1 Month',
    simple_guide TEXT DEFAULT '',
    is_active BOOLEAN DEFAULT true,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

DO $$ 
BEGIN 
    ALTER TABLE public.website_prices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY; 
EXCEPTION 
    WHEN others THEN NULL; 
END $$;

ALTER TABLE public.website_prices ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read website_prices" ON public.website_prices;
CREATE POLICY "Allow public read website_prices"
ON public.website_prices FOR SELECT TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS "Allow authenticated manage website_prices" ON public.website_prices;
CREATE POLICY "Allow authenticated manage website_prices"
ON public.website_prices FOR ALL TO authenticated
USING (true);

-- Insert Current Active Trading Services & NewsX AI Plans (Auto-IDs applied):
INSERT INTO public.website_prices (item_key, item_name, current_price, old_price, discount_tag, duration, simple_guide, is_active)
VALUES
    ('newsx_standard', 'NewsX AI Standard Monthly', 15, 25, 'Standard', '1 Month', 'NewsX Standard monthly automated analysis access', true),
    ('newsx_pro', 'NewsX AI Pro VIP Monthly', 25, 45, 'Popular', '1 Month', 'NewsX Pro VIP monthly access with instant Telegram alerts', true),
    ('newsx_ultimate', 'NewsX AI Ultimate Master', 50, 90, 'Elite', '1 Month', 'NewsX Ultimate Master access with 1-on-1 direct support', true),
    ('account_management', 'Institutional Account Management', 0, 0, '50/50 Split', 'Ongoing', 'Professional trading management on Exness Real accounts (50% / 50% profit split model)', true),
    ('vip_gold_signals', 'VIP Gold & Forex Daily Signals', 49, 99, '50% OFF', '1 Month', 'Daily high-probability signals on XAUUSD, Forex pairs, tight stop losses', true),
    ('mt5_indicator', 'Proprietary MT5 Volatility Indicator', 199, 350, 'Lifetime', 'Lifetime License', 'Custom algorithmic quantitative indicator for MT4/MT5, 0 repaint', true)
ON CONFLICT (item_key) DO UPDATE SET
    item_name = EXCLUDED.item_name,
    current_price = EXCLUDED.current_price,
    old_price = EXCLUDED.old_price,
    discount_tag = EXCLUDED.discount_tag,
    duration = EXCLUDED.duration,
    simple_guide = EXCLUDED.simple_guide,
    updated_at = timezone('utc'::text, now());


-- ------------------------------------------------------------------------------
-- ⚙️ TABLE 5: website_settings (إعدادات وروابط وقنوات التواصل للموقع)
-- Auto-ID: You DO NOT need to enter "id". It is generated automatically (1, 2, 3...)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.website_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_name TEXT UNIQUE NOT NULL,
    current_value TEXT NOT NULL,
    what_it_does TEXT,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

DO $$ 
BEGIN 
    ALTER TABLE public.website_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY; 
EXCEPTION 
    WHEN others THEN NULL; 
END $$;

ALTER TABLE public.website_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read website_settings" ON public.website_settings;
CREATE POLICY "Allow public read website_settings"
ON public.website_settings FOR SELECT TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS "Allow authenticated manage website_settings" ON public.website_settings;
CREATE POLICY "Allow authenticated manage website_settings"
ON public.website_settings FOR ALL TO authenticated
USING (true);

-- Insert Current Active Settings:
INSERT INTO public.website_settings (setting_name, current_value, what_it_does)
VALUES
    ('telegram_username', '@HNTSB15', 'Your official Telegram handle displayed across the website'),
    ('telegram_channel', 'https://t.me/HNTSB15', 'Your official Telegram channel or direct chat link'),
    ('support_email', 'saifeddine.jskyst15@gmail.com', 'Your official contact email'),
    ('whatsapp_number', '+213697114385', 'Your official WhatsApp phone number for client chat and leads'),
    ('instagram_profile', 'https://www.instagram.com/oo._.saifeddine._.oo/', 'Your official Instagram profile URL'),
    ('x_profile', 'https://x.com/seifeddin06', 'Your official X / Twitter profile URL'),
    ('bep20_deposit_wallet', '0x41f8a3a3a841cb3305bf1ebabe4ede7169a55bce', 'Your official BEP20 Binance Smart Chain wallet where clients send payments'),
    ('trc20_deposit_wallet', 'TEznkT5SKzYNHNe3wDEwfrxLpAq9HYA9sP', 'Your official TRC20 Tron wallet where clients send payments'),
    ('announcement_banner_text', '', 'Optional top alert banner message (leave empty to hide)'),
    ('announcement_banner_active', 'false', 'Enable (true) or disable (false) the top announcement banner')
ON CONFLICT (setting_name) DO UPDATE SET
    current_value = EXCLUDED.current_value,
    what_it_does = EXCLUDED.what_it_does,
    updated_at = timezone('utc'::text, now());


-- ------------------------------------------------------------------------------
-- 🌍 TABLE 6: website_visitors (إحصائيات الزوار وتحليلات الموقع)
-- Auto-ID: You DO NOT need to enter "id". It is generated automatically (1, 2, 3...)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.website_visitors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_time TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    ip_address TEXT,
    country TEXT,
    city TEXT,
    device_model TEXT,
    operating_system TEXT,
    browser TEXT,
    screen_size TEXT,
    language TEXT,
    source_referrer TEXT
);

DO $$ 
BEGIN 
    ALTER TABLE public.website_visitors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY; 
EXCEPTION 
    WHEN others THEN NULL; 
END $$;

ALTER TABLE public.website_visitors ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX IF NOT EXISTS website_visitors_unique_ip 
ON public.website_visitors (ip_address) 
WHERE ip_address IS NOT NULL AND ip_address != 'Direct Visitor';

DROP POLICY IF EXISTS "Allow public insert to website_visitors" ON public.website_visitors;
CREATE POLICY "Allow public insert to website_visitors"
ON public.website_visitors FOR INSERT TO anon, authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated read website_visitors" ON public.website_visitors;
CREATE POLICY "Allow authenticated read website_visitors"
ON public.website_visitors FOR SELECT TO authenticated
USING (true);

DROP POLICY IF EXISTS "Allow authenticated manage website_visitors" ON public.website_visitors;
CREATE POLICY "Allow authenticated manage website_visitors"
ON public.website_visitors FOR ALL TO authenticated
USING (true);

-- ==============================================================================
-- 🚀 ALL DONE!
-- Run this in your Supabase SQL Editor once.
-- Now, all tables have AUTOMATIC auto-incrementing IDs (1, 2, 3...).
-- When adding rows in Table Editor: LEAVE "id" BLANK and it fills automatically!
-- ==============================================================================
